// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("http://localhost/Proyectofinal_Antonio/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.name("correo")).click();
    driver.findElement(By.name("correo")).sendKeys("correo1@gmail.com");
    driver.findElement(By.name("contrasenia")).click();
    driver.findElement(By.name("contrasenia")).sendKeys("123");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    driver.findElement(By.id("contenedor")).click();
    driver.findElement(By.linkText("Cerrar sesion")).click();
    driver.findElement(By.id("contenedor")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    driver.findElement(By.id("contenedor")).click();
    driver.findElement(By.name("correo")).click();
    driver.findElement(By.name("correo")).sendKeys("correo1@gmail.com");
    driver.findElement(By.id("contenedor")).click();
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    driver.findElement(By.name("contrasenia")).click();
    driver.findElement(By.id("contenedor")).click();
    driver.findElement(By.name("contrasenia")).click();
    driver.findElement(By.name("contrasenia")).sendKeys("234421124");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    driver.findElement(By.cssSelector("body")).click();
  }
}
